spring.application.name=trends-service
spring.config.import=optional:file:.env[.properties]
server.port=${APPLICATION_PORT:3000}

passport.jwk-set-uri=${JWK_SET_URI:http://localhost:9999/.well-known/jwks.json}